### ISSUE TITLE
Have an idea to do i18n

### ISSUE THREAD

**Issue by puzzle9** [lxgr-linux/pokete#116]
**Is your feature request related to a problem? Please describe.**
my english is bad...

**Describe the solution you'd like**
add i18n

**Describe alternatives you've considered**
your (and or) me

**Additional context**
![image](https://user-images.githubusercontent.com/13518196/160329624-cf298e6e-8f4e-4ecd-abbd-28de7608ddf9.png)

**Comment by lxgr-linux** [comment]
Hello,
thanks for your idea, but I don't plan to add a translation to the game since it was intended to be in English only and since I only speak two languages properly this would be a very big effort, and will bring mostly problems because many textboxes are designed with the text they will contain in mind.
