### ISSUE TITLE
A few ideas to make the game more balanced

### ISSUE THREAD

**Issue by skylarmt** [lxgr-linux/pokete#133]
I have a few ideas to balance the game and make it more fun.

* Scale up XP when defeating an enemy with a higher level than the player. When I defeat a higher-level creature, I still only get maybe four XP. It's disappointing.  It's much easier to catch higher level creatures than it is to level up the weak ones you already have.
* Attacks that hit their target should deal at least 1 HP of damage.  I've gotten "stuck" a couple times attacking an enemy over and over without doing any damage. On one occasion, the enemy ran out of moves and lost with a nearly full HP bar.
* Confusion and paralysis should have a chance of "failing", allowing the affected creature to attack normally for the turn.
* Adjust NPC levels based on player's strongest creature, so you don't get stuck in unexpected level 30 vs level 11 fights (for example, the Electrode on Route 7).

**Comment by cognivore** [comment]
* Scale up XP -- I wouldn't like it. With a good strategy, you can dispatch high level poketes with low level poketes. I think that something like giving 1 XP for each difference in levels starting from 5 is OK.
* Round up damage -- Why? This nerfs heavily armoured poketes. Some poketes, I assume, would be built to soak up damage and have low AV.
* Confusion and paralysis have a chance of failing already. You just have to attempt to attack through them or, if you want to be safe, swap out currently selected pokete.
* Adjust NPC levels. You just didn't find a pokete which can help you beat Route 7 without taking damage. Also, it's bad game design. The world is alive and the PC is a part of it. Not the other way around.
I also level up my poketes because deck is limited to 6 slots and to progress, you have to have a good punching power.

**Comment by cognivore** [comment]
upd

I completed the arena with my highest pokete being lvl 20 and the highest opp lvl 34. It was challenging and fun!/

**Comment by lxgr-linux** [comment]
The xp scale and the fail chance for confusion etc. have been added.
