### ISSUE TITLE
Some conversations aren't surrounded by brackets

### ISSUE THREAD

**Issue by magnus-ISU** [lxgr-linux/pokete#180]
**Checklist**
I have:
- [X] Searched the Issues page for my problem/feature request
- [X] Updated all related software and Pokete it self

**Describe the bug**
Some conversations aren't surrounded by < angle brackets >

**To Reproduce**
1. Go to Cave Town
3.Defeat Trainer
4. `< You get $20`

**Expected behavior**
All conversations are surrounded by brackets on both sides. Make it impossible to screw up, have a method which takes a string and shows the string within brackets.

**Environment**
 - Pokete version: 0.7.2
 - Python version 3.10.5
 - Scrap engine version git aur package

**Comment by malnjayz** [comment]
Looks like a design choice to me, in the [trainers.py](https://github.com/lxgr-linux/pokete/blob/7e6fa888b1584d3c201b88e11df277ea138c2cf3/pokete_data/trainers.py) and [npcs.py](https://github.com/lxgr-linux/pokete/blob/7e6fa888b1584d3c201b88e11df277ea138c2cf3/pokete_data/npcs.py) all strings only have the initial bracket. I did find a potential typo tho, in line 222 there is a string starting with `>` instead of `<`. Nevertheless, adding style to Strings via the function that prints them might be a good idea if you ever want to change the appereance. If thats a feature @lxgr-linux wants to see I wouldn't mind implementing it.

**Comment by lxgr-linux** [comment]
> If thats a feature @lxgr-linux wants to see I wouldn't mind implementing it.

That would be great, I'm open for PRs.

> All conversations are surrounded by brackets on both sides.

This is intended, back then all texts in conversations had just the leading bracket, the trailing bracket was just added to to parts of the conversation that don't mark the end, to indicate that text will follow.

But yes @malnjayz the leading bracket can be incorporated into the printing method, just lie the trailing one is, but I just didn't do it yet.
