### ISSUE TITLE
Sound effects error on Raspberry Pi OS

### ISSUE THREAD

**Issue by synthic** [lxgr-linux/pokete#209]
This game is cool! I am playing it on a Raspberry Pi over SSH and it mostly works. However, it seems `playsound` doesn't function properly on Raspberry Pi OS. Anytime a battle starts or anything else causes a sound effect to be played, I get error messages across the screen referencing `playsound` very similar to the issue I have linked here. The game then continues fine after I hit a key. The fix is likely switching to `pygame` or another library. But for me it isn't really a huge issue, so I am actually wondering if you could simply add a `--no-sound` command line option or some other way to disable sound effects since I won't hear them while playing remotely anyway.

https://github.com/TaylorSMarks/playsound/issues/16

**Comment by lxgr-linux** [comment]
Thanks a lot for your report,

Removing playsound solves this issue, because playsound is just an optional dependency. Since you play via ssh anyways, the missing sound won't be a problem.
Maybe I should add a section to the README mentioning this.

Switching to another audio library is not really an option, because all the other audio libraries I tried, like pydub or simpleaudio, had some issues, like not working properly on my machine or being abandoned.
Despite playsound having it's own querks, best seen in this issue, playsound also is the most universal option for audio playback, since it supports multiple audio formats.
Also moving to pygame isn't an option, because this game was purposefully made to not rely on pygame.

But despite all this it's a good thing to know the audio won't work on raspberrypis at all.

**Comment by anothervictimofsurvivalinstinct** [comment]
I've had it on multiple computers where this issue will pop up - it's always resolved by installing python3-gst for your specific distro. Even on my raspberry pi.

**Comment by synthic** [comment]
Thanks for the explanation! I didn't realize playsound was optional, but now I uninstalled it and all is well.
