### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by zenhighzer** [lxgr-linux/pokete#252]
**Checklist**
I have:
$ pip install scrap_engine
$ git clone https://github.com/lxgr-linux/pokete.git
$ ./pokete/pokete.py

**Describe the bug**
./pokete/pokete.py 
  File "./pokete/pokete.py", line 130
    if (index := deck.deck(mvp.movemap, 6, "Your deck", True)) is None:
              ^
SyntaxError: invalid syntax

**To Reproduce**
./pokete/pokete.py 

**Expected behavior**
starting the game

**Environment**
 - OS: Linux Mint 19.1 Tessa
 - Python version:  2.7.17 & 3.6.9

**Comment by MaFeLP** [comment]
Hi @zenhighzer!

Python 3.10 is required to run pokete, a python version of 3.10 or newer is required (see the badges at the top of the ReadMe). To run the game, you could either use the latest Linux Mint 21 "Vanessa", or any other distribution based on Ubuntu 22.04 (or newer), which ship Python 3.10 by default. Otherwise, you could try to install the [flatpak version](https://flathub.org/apps/details/com.github.lxgr_linux.pokete).

Hope that helps!
